### ISSUE TITLE
Heartbeat last id is always zero

### ISSUE THREAD

**Issue by nazariyv** [danpaquin/coinbasepro-python#356] opened 2019-02-24 21:48 UTC
When using authenticated `WebsocketClient` and heartbeat channel, is everyone also getting last trade id: 0? (starting the socket, and then making trades, obviously).

```
import datetime as dt
import cbpro
import time
import json

sandbox_url = 'wss://ws-feed-public.sandbox.pro.coinbase.com'
pro_url = "wss://ws-feed.pro.coinbase.com/"

SOCKET_CONFIG = {'products': ['BTC-USD'],
                 'auth': True,
                 'api_key': api_key,
                 'api_secret': api_secret,
                 'api_passphrase': api_pass,
                 'channels': ['heartbeat'],
                 'url': sandbox_url}

class MyWebsocketClient(cbpro.WebsocketClient):
    def on_open(self):
        self.message_count = 0
        self.most_recent_message = ''

    def on_message(self, msg):
        print(json.dumps(msg, indent=4, sort_keys=True))
        self.message_count += 1
        self.most_recent_message = msg

    def on_close(self):
        print("-- Goodbye! --")

    def __repr__(self):
        pass

wsClient = MyWebsocketClient(**SOCKET_CONFIG)

wsClient.start()
print(wsClient.url, wsClient.products)

run_for_seconds = 60
start_time = dt.datetime.now()

while start_time + dt.timedelta(seconds=run_for_seconds) > dt.datetime.now():
#   print(wsClient)
    time.sleep(1)

wsClient.close()

if wsClient.error:
    sys.exit(1)
else:
    sys.exit(0)
```

and the output:

```
{
    "last_trade_id": 0,
    "product_id": "BTC-USD",
    "sequence": 40010849,
    "time": "2019-02-24T21:36:27.952326Z",
    "type": "heartbeat"
}
{
    "last_trade_id": 0,
    "product_id": "BTC-USD",
    "sequence": 40010856,
    "time": "2019-02-24T21:36:28.952355Z",
    "type": "heartbeat"
}
{
    "last_trade_id": 0,
    "product_id": "BTC-USD",
    "sequence": 40010862,
    "time": "2019-02-24T21:36:29.952290Z",
    "type": "heartbeat"
}
{
    "last_trade_id": 0,
    "product_id": "BTC-USD",
    "sequence": 40010862,
    "time": "2019-02-24T21:36:30.952335Z",
    "type": "heartbeat"
}
[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:2471) - data: None
```

that ssl error is worrisome too.

**Comment by nazariyv** [comment] 2019-02-24 21:48
and, yes, I have tried this on the normal market (non-sandbox). Same story

**Comment by nazariyv** [comment] 2019-02-24 21:55
new SSL error, 2 out of 2 times now wsClient exits with an error:
```
[SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2471) - data: None
```

**Comment by noah222** [comment] 2019-02-24 22:03
The heartbeat does not include trade IDs, but the 'matches' feed does. What happens if you subscribe to 'matches'? Be aware that the feed only shows live matches from the sandbox, and last time I checked there was not match activity happening very frequently, since it's all just test accounts.

**Comment by nazariyv** [comment] 2019-02-24 22:05
The heartbeat has this last_trade_id, which I was assuming, was my last order id? The issue is not in getting the trade ids. That I can get. The problem is in pinpointing when we have missed to get the match message because it was dropped. Coinbase API tells us that we should use heartbeat for that. But I do not understand how.

**Comment by nazariyv** [comment] 2019-02-24 22:06
One can for example get done before match, then we would we have dropped a match message. But what if we drop both the match and done. There must be a good way to pinpoint the dropped messages. And I was under the impression that heartbeat is such a mechanism.

**Comment by noah222** [comment] 2019-02-24 22:15
from coinbase pro docs: " Authenticated feed messages do not increment the sequence number. It is currently not possible to detect if an authenticated feed message was dropped. "

I check each order manually until it is filled or I cancel it, since i have not found another reliable method to 100% verify the order being filled. I think the feeds are set up to give a house advantage, and it takes some creativity to work around it.

**Comment by nazariyv** [comment] 2019-02-24 22:23
You mean you use REST? Do you do that to check if you missed match potentially? At what point would you do this though?

**Comment by noah222** [comment] 2019-02-24 22:39
I do something like this:
first submit an order using this danpaquin api and look at the JSON response to get the order id. 

Then save the order ids in a list. Then check them in a loop every minute or so using get_fills.

`OrderStatus = auth_client.get_fills(order_id=ID_tocheck[i])`

Move through the list and check each order id, and I do this frequently. Inspect the response stored in OrderStatus to see what happened. 

I apologize if this is patronizing in any way, just trying to be helpful by explaining what has worked for me.

**Comment by nazariyv** [comment] 2019-02-24 23:00
This is not patronizing at all! Thank you. It may be useful for me.

**Comment by mcardillo55** [comment] 2020-11-22 10:54
Seems like others have seen this as well: https://github.com/preichenberger/go-coinbasepro/issues/89

A user in that thread opened a bug report with Coinbase support, but it seems the issue is still there.

Closing this for now, as it seems to be on the Coinbase side.

**Closed by mcardillo55** 2020-11-22 10:54 UTC
